---
apiVersion: v1
kind: Namespace
metadata:
  name: hornet
  labels: 
    name: hornet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hornet
  namespace: hornet
  labels:
    app: hornet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hornet
  template:
    metadata:
      labels:
        app: hornet
    spec:
      terminationGracePeriodSeconds: 240
      hostNetwork: false
      containers:
      - name: hornet
        image: "{image-hornet}"
        ports:
          - name: dashboard
            protocol: TCP
            containerPort: 8081
          - name: api
            protocol: TCP
            containerPort: 14265
          - name: peering
            protocol: TCP
            containerPort: 31200
          - name: autopeering
            protocol: UDP
            containerPort: 31201
        livenessProbe:
          tcpSocket:
            port: 15600
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 2
        readinessProbe:
          tcpSocket:
            port: 15600
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 2
      securityContext:
        fsGroup: 39999
---
kind: Service
apiVersion: v1
metadata:
  name: hornet-service
  namespace: hornet
spec:
  selector:
    app: hornet
  ports:
    - protocol: TCP
      port: 14265
      nodePort: 31115
      name: api
    - protocol: TCP
      port: 8081
      nodePort: 31111
      name: dashboard
    - protocol: TCP
      port: 31200
      nodePort: 31200
      name: peering
    - protocol: UDP
      port: 31201
      nodePort: 31201
      name: autopeering
  type: NodePort
